-- MySQL Script generated by MySQL Workbench
-- 04/28/15 10:57:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `OrtNR` INT NOT NULL,
  `Strasse` VARCHAR(60) NOT NULL,
  `PLZ` VARCHAR(4) NOT NULL,
  `Ort` VARCHAR(45) NOT NULL,
  `Hausnummer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OrtNR`),
  UNIQUE INDEX `idOrt_UNIQUE` (`OrtNR` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nutzer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nutzer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nutzer` (
  `NutzerID` INT NOT NULL,
  `VName` VARCHAR(45) NOT NULL,
  `NName` VARCHAR(45) NOT NULL,
  `NGeschl` TINYINT(1) NOT NULL,
  `Nutzercol` VARCHAR(45) NULL,
  `OrtNR` INT NOT NULL,
  `Admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`NutzerID`, `OrtNR`),
  INDEX `fk_Nutzer_Location1_idx` (`OrtNR` ASC),
  UNIQUE INDEX `NutzerID_UNIQUE` (`NutzerID` ASC),
  CONSTRAINT `fk_Nutzer_Location1`
    FOREIGN KEY (`OrtNR`)
    REFERENCES `mydb`.`Location` (`OrtNR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buchung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Buchung` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Buchung` (
  `BelegNR` VARCHAR(10) NOT NULL,
  `Rechnungsdatum` DATETIME NOT NULL,
  `Buchungsdatum` DATETIME NOT NULL,
  `Betriebsanteil` DOUBLE NOT NULL,
  `USt` INT NOT NULL,
  `NutzerID` INT NOT NULL,
  `OrtNR` INT NOT NULL,
  PRIMARY KEY (`BelegNR`, `NutzerID`, `OrtNR`),
  UNIQUE INDEX `Belegnummer_UNIQUE` (`BelegNR` ASC),
  INDEX `fk_Buchung_Nutzer1_idx` (`NutzerID` ASC, `OrtNR` ASC),
  CONSTRAINT `fk_Buchung_Nutzer1`
    FOREIGN KEY (`NutzerID` , `OrtNR`)
    REFERENCES `mydb`.`Nutzer` (`NutzerID` , `OrtNR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fahrt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fahrt` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fahrt` (
  `FahrtNR` INT NOT NULL,
  `DatumDerFahrt` DATETIME NOT NULL,
  `Anfangskilometerstand` DOUBLE NOT NULL,
  `Endkilometerstand` DOUBLE NOT NULL,
  `Abfahrtsort` INT NOT NULL,
  `Ankunftsort` INT NOT NULL,
  PRIMARY KEY (`FahrtNR`, `Abfahrtsort`, `Ankunftsort`),
  UNIQUE INDEX `FahrtNR_UNIQUE` (`FahrtNR` ASC),
  INDEX `fk_Fahrt_Location_idx` (`Abfahrtsort` ASC),
  INDEX `fk_Fahrt_Location1_idx` (`Ankunftsort` ASC),
  CONSTRAINT `fk_Fahrt_Location`
    FOREIGN KEY (`Abfahrtsort`)
    REFERENCES `mydb`.`Location` (`OrtNR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fahrt_Location1`
    FOREIGN KEY (`Ankunftsort`)
    REFERENCES `mydb`.`Location` (`OrtNR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anschaffung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Anschaffung` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Anschaffung` (
  `AnschaffungsNR` INT NOT NULL,
  `Verwendungszweck` VARCHAR(45) NOT NULL,
  `Anschaffungsdatum` DATETIME NOT NULL,
  `Anschaffungswert` DOUBLE NOT NULL,
  `Bilanzwert` DOUBLE NOT NULL,
  `NutzerID` INT NOT NULL,
  `OrtNR` INT NOT NULL,
  PRIMARY KEY (`AnschaffungsNR`, `NutzerID`, `OrtNR`),
  UNIQUE INDEX `AnschaffungsNR_UNIQUE` (`AnschaffungsNR` ASC),
  INDEX `fk_Anschaffung_Nutzer1_idx` (`NutzerID` ASC, `OrtNR` ASC),
  CONSTRAINT `fk_Anschaffung_Nutzer1`
    FOREIGN KEY (`NutzerID` , `OrtNR`)
    REFERENCES `mydb`.`Nutzer` (`NutzerID` , `OrtNR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Abteilung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Abteilung` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Abteilung` (
  `AKz` VARCHAR(3) NOT NULL,
  `ABezeichnung` VARCHAR(45) NOT NULL,
  `NutzerID` INT NOT NULL,
  PRIMARY KEY (`AKz`, `NutzerID`),
  UNIQUE INDEX `AKz_UNIQUE` (`AKz` ASC),
  INDEX `fk_Abteilung_Nutzer1_idx` (`NutzerID` ASC),
  CONSTRAINT `fk_Abteilung_Nutzer1`
    FOREIGN KEY (`NutzerID`)
    REFERENCES `mydb`.`Nutzer` (`NutzerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AfA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AfA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AfA` (
  `AfANR` INT NOT NULL,
  `Dauer` INT NULL,
  `Prozentsatz` INT NULL,
  `AnschaffungsNR` INT NOT NULL,
  PRIMARY KEY (`AfANR`, `AnschaffungsNR`),
  UNIQUE INDEX `AfANR_UNIQUE` (`AfANR` ASC),
  INDEX `fk_AfA_Anschaffung1_idx` (`AnschaffungsNR` ASC),
  CONSTRAINT `fk_AfA_Anschaffung1`
    FOREIGN KEY (`AnschaffungsNR`)
    REFERENCES `mydb`.`Anschaffung` (`AnschaffungsNR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kunde`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kunde` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kunde` (
  `KundenID` INT NOT NULL,
  `KundenKz` VARCHAR(10) NOT NULL,
  `KBezeichnung` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`KundenID`),
  UNIQUE INDEX `idKunde_UNIQUE` (`KundenID` ASC),
  UNIQUE INDEX `KundenKz_UNIQUE` (`KundenKz` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
